### ISSUE TITLE
NFT minting not working from phantom and solflare

### ISSUE THREAD

**Issue by 0xPratik** [solana-mobile/Minty-fresh#322]
I am trying to mint the NFT using phantom but it's not working somehow. I have set phantom to devnet and i have enough Devnet SOL.
here is a demo explaining that the issue is
https://user-images.githubusercontent.com/62953475/220715719-dbb6032a-3921-46d9-9677-e71d5af71160.mp4

**Comment by Funkatronics** [comment]
Pratik reported that Solflare is exhibiting the same behavior as well. I have not been able to reproduce on my end

**Comment by Funkatronics** [comment]
Device: Samsung s20 FE Android 13

**Comment by SanjaySargam** [comment]
Not able to reproduce

Device: Realme 9 Android 13
